apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBroker
metadata:
  name: privileged-automation-broker
  namespace: foo
spec:
  url: "https://automation-broker.automation-broker.svc:1338/automation-broker/"
  authInfo:
    bearer:
      secretRef:
        kind: Secret
        namespace: foo
        name: %%CLIENT_TOKEN_NAME%%
  caBundle: %%BROKER_CA_CERT%%
